### PR TITLE
Added characters property which provides a list of characters

### PR DESCRIPTION
**Pull request by binsento42**
Added a property to the anime class (anime.characters) that provides a list of character names as appearing in the 'Characters and Actors' overview. The list only contains the fictional names, not the voice actors. The corresponding test is also added to the unit test.

### CODE REVIEW

**Comment by darenliang** [comment]
Thanks for your contribution.

I just have a few questions about this pull request.

* Would it be better to include voice actors and rename the property to something like `.characters_and_voice_actors`?
* Since the code used to extract characters could be used to extract staff data, would it make sense to add a `.staff` property?
* Could the `.characters` property be added to the manga class?

It would be best to not miss any addable properties and maintain backwards compatibility in the case that voice actors are added. My hope is that these features get released as version 0.4.0.

Please let me know your thoughts, I'm willing to work on some of the changes if needed.

**Comment by binsento42** [comment]
Hello Daren,

I simple needed the characters, so that was my focus. It's always quite a
struggle to find the right tags to scrape the mal pages. Getting the
characters was pretty doable, but I was not sure how to link them to the
voice actors in the html, they don't seem linked at all by any parent.
That's why I didn't add it.

I'm not sure about the manga, a quick glance at the source doesn't reveal
any hooks to get the character names from the manga page. So it might be a
logical request, but not straightforward.

kind regards,
Vincent

**Comment by darenliang** [comment]
Thanks for letting me know.

I'll look into how it might be possible and I'll get back to you as soon as possible.

**Comment by binsento42** [comment]
This pull request can be closed because the discussed functionality is already implemented in the fork.

**Pull request closed without merging**
