### PR TITLE
Functionality changed and added as discussed in previous pull request

### PR DESCRIPTION
**Pull request by binsento42**
Added functionality compared to the master:
- added a 'debug' mode to the base class for faster testing which caches the page on disk and uses this cache for testing (fully backwards compatible, debug option can be ommited)
- added anime.staff
- added manga.characters
- added anime 'Character' object with attributes name and actor and __str__ and __repr__ methods
- added anime.characters where character is an Anime.Character object (as above)
- updated README

Since this replaces the previous pull request #14 I've cancelled that request.

### CODE REVIEW

**Comment by binsento42** [comment]
I forgot to update the automated tests...

**Comment by darenliang** [comment]
Looks good. There are a few things I would like to be touched up so I'll open some pull requests on your fork before this gets merged and released.

**Comment by binsento42** [comment]
Great!

**Comment by darenliang** [comment]
I think the debug idea is great but it doesn't fit well with this commit.

I'll look to add auto-documentation so it'll be easier for people to use the `.characters` and `.staff` properties.

**Comment by binsento42** [comment]
I understand, I didn't think about that but I just added the debug because
it made the testing a lot quicker. By that time I had the tags almost
figured out though, but still. It is a bit of a hassle that python errors
occuring in the parsing methods don't seem to show up, I suspected because
of a try catch somewhere higher up..

I think you have done a great job on the refactoring, nice coding!

kind regards,
Vincent

**Comment by darenliang** [comment]
Thank you for understanding. I'll merge the pr and try adding ReadTheDocs integration before pushing 0.4.0.

**Pull request merged**
